// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pehredaar/pehredaar.proto

package pehredaar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Attribute struct {
	Skip                 bool     `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f0185de09cffbe, []int{0}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

type MyRights struct {
	Resource              []string `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	ResourceAnd           []string `protobuf:"bytes,2,rep,name=resource_and,json=resourceAnd,proto3" json:"resource_and,omitempty"`
	ResourceStatic        []string `protobuf:"bytes,3,rep,name=resource_static,json=resourceStatic,proto3" json:"resource_static,omitempty"`
	ResourceStaticDefault bool     `protobuf:"varint,4,opt,name=resource_static_default,json=resourceStaticDefault,proto3" json:"resource_static_default,omitempty"`
	OnlyAttributeBased    bool     `protobuf:"varint,5,opt,name=only_attribute_based,json=onlyAttributeBased,proto3" json:"only_attribute_based,omitempty"`
	AllowParent           bool     `protobuf:"varint,6,opt,name=allow_parent,json=allowParent,proto3" json:"allow_parent,omitempty"`
	AllowStaff            bool     `protobuf:"varint,7,opt,name=allow_staff,json=allowStaff,proto3" json:"allow_staff,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MyRights) Reset()         { *m = MyRights{} }
func (m *MyRights) String() string { return proto.CompactTextString(m) }
func (*MyRights) ProtoMessage()    {}
func (*MyRights) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f0185de09cffbe, []int{1}
}

func (m *MyRights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyRights.Unmarshal(m, b)
}
func (m *MyRights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyRights.Marshal(b, m, deterministic)
}
func (m *MyRights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyRights.Merge(m, src)
}
func (m *MyRights) XXX_Size() int {
	return xxx_messageInfo_MyRights.Size(m)
}
func (m *MyRights) XXX_DiscardUnknown() {
	xxx_messageInfo_MyRights.DiscardUnknown(m)
}

var xxx_messageInfo_MyRights proto.InternalMessageInfo

func (m *MyRights) GetResource() []string {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *MyRights) GetResourceAnd() []string {
	if m != nil {
		return m.ResourceAnd
	}
	return nil
}

func (m *MyRights) GetResourceStatic() []string {
	if m != nil {
		return m.ResourceStatic
	}
	return nil
}

func (m *MyRights) GetResourceStaticDefault() bool {
	if m != nil {
		return m.ResourceStaticDefault
	}
	return false
}

func (m *MyRights) GetOnlyAttributeBased() bool {
	if m != nil {
		return m.OnlyAttributeBased
	}
	return false
}

func (m *MyRights) GetAllowParent() bool {
	if m != nil {
		return m.AllowParent
	}
	return false
}

func (m *MyRights) GetAllowStaff() bool {
	if m != nil {
		return m.AllowStaff
	}
	return false
}

type ServicePattern struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServicePattern) Reset()         { *m = ServicePattern{} }
func (m *ServicePattern) String() string { return proto.CompactTextString(m) }
func (*ServicePattern) ProtoMessage()    {}
func (*ServicePattern) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f0185de09cffbe, []int{2}
}

func (m *ServicePattern) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServicePattern.Unmarshal(m, b)
}
func (m *ServicePattern) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServicePattern.Marshal(b, m, deterministic)
}
func (m *ServicePattern) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServicePattern.Merge(m, src)
}
func (m *ServicePattern) XXX_Size() int {
	return xxx_messageInfo_ServicePattern.Size(m)
}
func (m *ServicePattern) XXX_DiscardUnknown() {
	xxx_messageInfo_ServicePattern.DiscardUnknown(m)
}

var xxx_messageInfo_ServicePattern proto.InternalMessageInfo

func (m *ServicePattern) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type ModuleRole struct {
	ModuleRoleName       string   `protobuf:"bytes,1,opt,name=module_role_name,json=moduleRoleName,proto3" json:"module_role_name,omitempty"`
	DisplayName          string   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Pattern              []string `protobuf:"bytes,3,rep,name=pattern,proto3" json:"pattern,omitempty"`
	ServiceName          string   `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	SkipServiceName      bool     `protobuf:"varint,5,opt,name=skip_service_name,json=skipServiceName,proto3" json:"skip_service_name,omitempty"`
	Rpc                  []string `protobuf:"bytes,6,rep,name=rpc,proto3" json:"rpc,omitempty"`
	GroupingAllowed      bool     `protobuf:"varint,7,opt,name=grouping_allowed,json=groupingAllowed,proto3" json:"grouping_allowed,omitempty"`
	Priority             int32    `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"`
	Description          string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	External             bool     `protobuf:"varint,10,opt,name=external,proto3" json:"external,omitempty"`
	AppName              string   `protobuf:"bytes,11,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleRole) Reset()         { *m = ModuleRole{} }
func (m *ModuleRole) String() string { return proto.CompactTextString(m) }
func (*ModuleRole) ProtoMessage()    {}
func (*ModuleRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f0185de09cffbe, []int{3}
}

func (m *ModuleRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleRole.Unmarshal(m, b)
}
func (m *ModuleRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleRole.Marshal(b, m, deterministic)
}
func (m *ModuleRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleRole.Merge(m, src)
}
func (m *ModuleRole) XXX_Size() int {
	return xxx_messageInfo_ModuleRole.Size(m)
}
func (m *ModuleRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleRole.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleRole proto.InternalMessageInfo

func (m *ModuleRole) GetModuleRoleName() string {
	if m != nil {
		return m.ModuleRoleName
	}
	return ""
}

func (m *ModuleRole) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *ModuleRole) GetPattern() []string {
	if m != nil {
		return m.Pattern
	}
	return nil
}

func (m *ModuleRole) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ModuleRole) GetSkipServiceName() bool {
	if m != nil {
		return m.SkipServiceName
	}
	return false
}

func (m *ModuleRole) GetRpc() []string {
	if m != nil {
		return m.Rpc
	}
	return nil
}

func (m *ModuleRole) GetGroupingAllowed() bool {
	if m != nil {
		return m.GroupingAllowed
	}
	return false
}

func (m *ModuleRole) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *ModuleRole) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ModuleRole) GetExternal() bool {
	if m != nil {
		return m.External
	}
	return false
}

func (m *ModuleRole) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

type ModuleRoles struct {
	ModuleRole           []*ModuleRole `protobuf:"bytes,1,rep,name=module_role,json=moduleRole,proto3" json:"module_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ModuleRoles) Reset()         { *m = ModuleRoles{} }
func (m *ModuleRoles) String() string { return proto.CompactTextString(m) }
func (*ModuleRoles) ProtoMessage()    {}
func (*ModuleRoles) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4f0185de09cffbe, []int{4}
}

func (m *ModuleRoles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleRoles.Unmarshal(m, b)
}
func (m *ModuleRoles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleRoles.Marshal(b, m, deterministic)
}
func (m *ModuleRoles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleRoles.Merge(m, src)
}
func (m *ModuleRoles) XXX_Size() int {
	return xxx_messageInfo_ModuleRoles.Size(m)
}
func (m *ModuleRoles) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleRoles.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleRoles proto.InternalMessageInfo

func (m *ModuleRoles) GetModuleRole() []*ModuleRole {
	if m != nil {
		return m.ModuleRole
	}
	return nil
}

var E_Paths = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MyRights)(nil),
	Field:         9955,
	Name:          "pehredaar.paths",
	Tag:           "bytes,9955,opt,name=paths",
	Filename:      "pehredaar/pehredaar.proto",
}

var E_Pattern = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.ServiceOptions)(nil),
	ExtensionType: (*ServicePattern)(nil),
	Field:         9696,
	Name:          "pehredaar.pattern",
	Tag:           "bytes,9696,opt,name=pattern",
	Filename:      "pehredaar/pehredaar.proto",
}

var E_Attribute = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*Attribute)(nil),
	Field:         9956,
	Name:          "pehredaar.attribute",
	Tag:           "bytes,9956,opt,name=attribute",
	Filename:      "pehredaar/pehredaar.proto",
}

var E_ModuleRoles = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FileOptions)(nil),
	ExtensionType: (*ModuleRoles)(nil),
	Field:         9779,
	Name:          "pehredaar.module_roles",
	Tag:           "bytes,9779,opt,name=module_roles",
	Filename:      "pehredaar/pehredaar.proto",
}

func init() {
	proto.RegisterType((*Attribute)(nil), "pehredaar.Attribute")
	proto.RegisterType((*MyRights)(nil), "pehredaar.MyRights")
	proto.RegisterType((*ServicePattern)(nil), "pehredaar.ServicePattern")
	proto.RegisterType((*ModuleRole)(nil), "pehredaar.ModuleRole")
	proto.RegisterType((*ModuleRoles)(nil), "pehredaar.ModuleRoles")
	proto.RegisterExtension(E_Paths)
	proto.RegisterExtension(E_Pattern)
	proto.RegisterExtension(E_Attribute)
	proto.RegisterExtension(E_ModuleRoles)
}

func init() { proto.RegisterFile("pehredaar/pehredaar.proto", fileDescriptor_e4f0185de09cffbe) }

var fileDescriptor_e4f0185de09cffbe = []byte{
	// 614 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0x55, 0xd2, 0xbf, 0xe4, 0x4e, 0xd5, 0xf6, 0xf3, 0xd7, 0x82, 0x5b, 0x01, 0x0d, 0xd9, 0x10,
	0xba, 0x48, 0x51, 0x91, 0xba, 0xc8, 0xae, 0x15, 0xb0, 0x00, 0x02, 0xd5, 0x44, 0x48, 0x88, 0xcd,
	0xc8, 0xc9, 0x38, 0xc9, 0x08, 0x67, 0x6c, 0xd9, 0x0e, 0x90, 0xb7, 0xe1, 0x1d, 0x78, 0x21, 0x24,
	0x78, 0x04, 0x1e, 0x00, 0xf9, 0x7a, 0xc6, 0x33, 0xa1, 0xdd, 0xf9, 0x9e, 0x7b, 0xee, 0x99, 0xe3,
	0x63, 0x7b, 0xe0, 0x58, 0xf1, 0xb9, 0xe6, 0x29, 0x63, 0xfa, 0x3c, 0xac, 0xfa, 0x4a, 0x4b, 0x2b,
	0x49, 0x3b, 0x00, 0x27, 0x9d, 0x99, 0x94, 0x33, 0xc1, 0xcf, 0xb1, 0x31, 0x5e, 0x4e, 0xcf, 0x53,
	0x6e, 0x26, 0x3a, 0x53, 0x56, 0x16, 0xe4, 0xee, 0x29, 0xb4, 0xaf, 0xac, 0xd5, 0xd9, 0x78, 0x69,
	0x39, 0x21, 0xb0, 0x69, 0x3e, 0x67, 0x8a, 0x36, 0x3a, 0x8d, 0x5e, 0x2b, 0xc6, 0x75, 0xf7, 0x7b,
	0x13, 0x5a, 0xc3, 0x55, 0x9c, 0xcd, 0xe6, 0xd6, 0x90, 0x13, 0x68, 0x69, 0x6e, 0xe4, 0x52, 0x4f,
	0x38, 0x6d, 0x74, 0x36, 0x7a, 0xed, 0x38, 0xd4, 0xe4, 0x31, 0xec, 0x96, 0xeb, 0x84, 0xe5, 0x29,
	0x6d, 0x62, 0x3f, 0x2a, 0xb1, 0xab, 0x3c, 0x25, 0x4f, 0x60, 0x3f, 0x50, 0x8c, 0x65, 0x36, 0x9b,
	0xd0, 0x0d, 0x64, 0xed, 0x95, 0xf0, 0x08, 0x51, 0x72, 0x09, 0xf7, 0xff, 0x21, 0x26, 0x29, 0x9f,
	0xb2, 0xa5, 0xb0, 0x74, 0x13, 0xbd, 0x1d, 0xad, 0x0f, 0xbc, 0xf0, 0x4d, 0xf2, 0x0c, 0x0e, 0x65,
	0x2e, 0x56, 0x09, 0x2b, 0xb7, 0x94, 0x8c, 0x99, 0xe1, 0x29, 0xdd, 0xc2, 0x21, 0xe2, 0x7a, 0x61,
	0xb7, 0xd7, 0xae, 0xe3, 0x5c, 0x33, 0x21, 0xe4, 0xd7, 0x44, 0x31, 0xcd, 0x73, 0x4b, 0xb7, 0x91,
	0x19, 0x21, 0x76, 0x83, 0x10, 0x39, 0x05, 0x5f, 0x3a, 0x27, 0xd3, 0x29, 0xdd, 0x41, 0x06, 0x20,
	0x34, 0x72, 0x48, 0xf7, 0x0c, 0xf6, 0x46, 0x5c, 0x7f, 0xc9, 0x26, 0xfc, 0x86, 0x59, 0xcb, 0x75,
	0x4e, 0x28, 0xec, 0x28, 0xbf, 0xc4, 0x2c, 0xdb, 0x71, 0x59, 0x76, 0xff, 0x34, 0x01, 0x86, 0x32,
	0x5d, 0x0a, 0x1e, 0x4b, 0xc1, 0x49, 0x0f, 0x0e, 0x16, 0x58, 0x25, 0x5a, 0x0a, 0x9e, 0xe4, 0x6c,
	0xc1, 0x8b, 0x89, 0xbd, 0x45, 0x60, 0xbd, 0x63, 0x0b, 0x8c, 0x37, 0xcd, 0x8c, 0x12, 0x6c, 0xe5,
	0x59, 0x4d, 0x64, 0x45, 0x05, 0x86, 0x94, 0xda, 0x57, 0x7d, 0xac, 0x65, 0xe9, 0x86, 0x8d, 0x77,
	0xe8, 0x87, 0x37, 0xfd, 0x70, 0x81, 0xe1, 0xf0, 0x19, 0xfc, 0xe7, 0xce, 0x3b, 0x59, 0xe3, 0xf9,
	0xdc, 0xf6, 0x5d, 0x63, 0x54, 0xe3, 0x1e, 0xc0, 0x86, 0x56, 0x13, 0xba, 0x8d, 0x1f, 0x71, 0x4b,
	0xf2, 0x14, 0x0e, 0x66, 0x5a, 0x2e, 0x55, 0x96, 0xcf, 0x12, 0x4c, 0x86, 0xa7, 0x45, 0x50, 0xfb,
	0x25, 0x7e, 0xe5, 0x61, 0x77, 0x87, 0x94, 0xce, 0xa4, 0xce, 0xec, 0x8a, 0xb6, 0x3a, 0x8d, 0xde,
	0x56, 0x1c, 0x6a, 0xd2, 0x81, 0xa8, 0xbc, 0xa1, 0x99, 0xcc, 0x69, 0xbb, 0xd8, 0x63, 0x05, 0xb9,
	0x69, 0xfe, 0xcd, 0xed, 0x89, 0x09, 0x0a, 0xf8, 0x81, 0x50, 0x93, 0x63, 0x68, 0x31, 0xa5, 0xbc,
	0xf3, 0xc8, 0xc7, 0xce, 0x94, 0x72, 0x8e, 0xbb, 0x2f, 0x21, 0xaa, 0x52, 0x37, 0xe4, 0x12, 0xa2,
	0x5a, 0xec, 0x78, 0x95, 0xa3, 0x8b, 0xa3, 0x7e, 0xf5, 0x92, 0x2a, 0x72, 0x0c, 0xd5, 0x41, 0x0c,
	0x5e, 0xc3, 0x96, 0x62, 0x76, 0x6e, 0xc8, 0xa3, 0xbe, 0x7f, 0x59, 0xfd, 0xf2, 0x65, 0xf5, 0x87,
	0xdc, 0xce, 0x65, 0xfa, 0x1e, 0x5d, 0x1a, 0xfa, 0x6b, 0xd8, 0x69, 0xf4, 0xa2, 0x8b, 0xff, 0xeb,
	0x92, 0xc5, 0x23, 0x8a, 0xbd, 0xc4, 0xe0, 0x43, 0x38, 0x2d, 0x72, 0x7a, 0x4b, 0xad, 0x48, 0xbb,
	0x94, 0xfb, 0xf9, 0x06, 0xe5, 0x8e, 0x6b, 0x72, 0xeb, 0x37, 0x2e, 0x1c, 0xf5, 0x20, 0x86, 0x76,
	0xb8, 0xfd, 0xe4, 0xe1, 0x2d, 0xe1, 0x57, 0x19, 0x17, 0xc1, 0xe5, 0x6f, 0xef, 0xf2, 0xb0, 0x26,
	0x1b, 0x9e, 0x47, 0x5c, 0xc9, 0x0c, 0x3e, 0xc2, 0x6e, 0x2d, 0x2e, 0x43, 0x1e, 0xdc, 0x21, 0x2b,
	0x82, 0xd9, 0x1f, 0x6f, 0x51, 0xf5, 0xde, 0x9d, 0x71, 0x9a, 0x38, 0xaa, 0xf2, 0x34, 0xd7, 0xd1,
	0xa7, 0xea, 0x6f, 0x35, 0xde, 0x46, 0xb9, 0xe7, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x66, 0x47,
	0xe4, 0x90, 0xdc, 0x04, 0x00, 0x00,
}
