// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/proto/rightsval/validator.proto

package rightsval // import "pb/rightsval"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyRights struct {
	Resource             []string `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyRights) Reset()         { *m = MyRights{} }
func (m *MyRights) String() string { return proto.CompactTextString(m) }
func (*MyRights) ProtoMessage()    {}
func (*MyRights) Descriptor() ([]byte, []int) {
	return fileDescriptor_validator_82a9f1b8a99fb010, []int{0}
}
func (m *MyRights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyRights.Unmarshal(m, b)
}
func (m *MyRights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyRights.Marshal(b, m, deterministic)
}
func (dst *MyRights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyRights.Merge(dst, src)
}
func (m *MyRights) XXX_Size() int {
	return xxx_messageInfo_MyRights.Size(m)
}
func (m *MyRights) XXX_DiscardUnknown() {
	xxx_messageInfo_MyRights.DiscardUnknown(m)
}

var xxx_messageInfo_MyRights proto.InternalMessageInfo

func (m *MyRights) GetResource() []string {
	if m != nil {
		return m.Resource
	}
	return nil
}

var E_Validator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MyRights)(nil),
	Field:         9955,
	Name:          "rightsval.validator",
	Tag:           "bytes,9955,opt,name=validator",
	Filename:      "example/proto/rightsval/validator.proto",
}

func init() {
	proto.RegisterType((*MyRights)(nil), "rightsval.MyRights")
	proto.RegisterExtension(E_Validator)
}

func init() {
	proto.RegisterFile("example/proto/rightsval/validator.proto", fileDescriptor_validator_82a9f1b8a99fb010)
}

var fileDescriptor_validator_82a9f1b8a99fb010 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0xca, 0x4c, 0xcf, 0x28, 0x29,
	0x2e, 0x4b, 0xcc, 0xd1, 0x2f, 0x4b, 0xcc, 0xc9, 0x4c, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x03, 0xcb,
	0x08, 0x71, 0xc2, 0xa5, 0xa4, 0x14, 0xd2, 0xf3, 0xf3, 0xd3, 0x61, 0x5a, 0x92, 0x4a, 0xd3, 0xf4,
	0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0xe0, 0x8a, 0x95, 0xd4, 0xb8, 0x38, 0x7c, 0x2b, 0x83,
	0xc0, 0x1a, 0x84, 0xa4, 0xb8, 0x38, 0x8a, 0x52, 0x8b, 0xf3, 0x4b, 0x8b, 0x92, 0x53, 0x25, 0x18,
	0x15, 0x98, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0xab, 0x20, 0x2e, 0x4e, 0xb8, 0x3d, 0x42, 0x72, 0x7a,
	0x10, 0x73, 0xf5, 0x60, 0xe6, 0xea, 0xf9, 0xa6, 0x96, 0x64, 0xe4, 0xa7, 0xf8, 0x17, 0x94, 0x64,
	0xe6, 0xe7, 0x15, 0x4b, 0x3c, 0xf6, 0x55, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd6, 0x83, 0xbb, 0x44,
	0x0f, 0x66, 0x49, 0x10, 0xc2, 0x18, 0x27, 0xbe, 0x28, 0x9e, 0x82, 0x24, 0x84, 0x47, 0x92, 0xd8,
	0xc0, 0xc6, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x76, 0xdb, 0x38, 0x51, 0xea, 0x00, 0x00,
	0x00,
}
