// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/pehredaar/pehredaar.proto

package pehredaar

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MyRights struct {
	Resource             []string `protobuf:"bytes,1,rep,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyRights) Reset()         { *m = MyRights{} }
func (m *MyRights) String() string { return proto.CompactTextString(m) }
func (*MyRights) ProtoMessage()    {}
func (*MyRights) Descriptor() ([]byte, []int) {
	return fileDescriptor_a6e3f9da501351c6, []int{0}
}

func (m *MyRights) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyRights.Unmarshal(m, b)
}
func (m *MyRights) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyRights.Marshal(b, m, deterministic)
}
func (m *MyRights) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyRights.Merge(m, src)
}
func (m *MyRights) XXX_Size() int {
	return xxx_messageInfo_MyRights.Size(m)
}
func (m *MyRights) XXX_DiscardUnknown() {
	xxx_messageInfo_MyRights.DiscardUnknown(m)
}

var xxx_messageInfo_MyRights proto.InternalMessageInfo

func (m *MyRights) GetResource() []string {
	if m != nil {
		return m.Resource
	}
	return nil
}

var E_Paths = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MethodOptions)(nil),
	ExtensionType: (*MyRights)(nil),
	Field:         9955,
	Name:          "pehredaar.paths",
	Tag:           "bytes,9955,opt,name=paths",
	Filename:      "src/pehredaar/pehredaar.proto",
}

func init() {
	proto.RegisterType((*MyRights)(nil), "pehredaar.MyRights")
	proto.RegisterExtension(E_Paths)
}

func init() { proto.RegisterFile("src/pehredaar/pehredaar.proto", fileDescriptor_a6e3f9da501351c6) }

var fileDescriptor_a6e3f9da501351c6 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x2e, 0x4a, 0xd6,
	0x2f, 0x48, 0xcd, 0x28, 0x4a, 0x4d, 0x49, 0x4c, 0x2c, 0x42, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0xe1, 0x02, 0x52, 0x0a, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x60, 0x89,
	0xa4, 0xd2, 0x34, 0xfd, 0x94, 0xd4, 0xe2, 0xe4, 0xa2, 0xcc, 0x82, 0x92, 0x7c, 0xa8, 0x62, 0x25,
	0x35, 0x2e, 0x0e, 0xdf, 0xca, 0xa0, 0xcc, 0xf4, 0x8c, 0x92, 0x62, 0x21, 0x29, 0x2e, 0x8e, 0xa2,
	0xd4, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4, 0x54, 0x09, 0x46, 0x05, 0x66, 0x0d, 0xce, 0x20, 0x38, 0xdf,
	0xca, 0x8b, 0x8b, 0xb5, 0x20, 0xb1, 0x24, 0xa3, 0x58, 0x48, 0x4e, 0x0f, 0x62, 0xa6, 0x1e, 0xcc,
	0x4c, 0x3d, 0xdf, 0xd4, 0x92, 0x8c, 0xfc, 0x14, 0xff, 0x82, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x89,
	0xc7, 0xbe, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xc2, 0x7a, 0x08, 0x67, 0xc1, 0x2c, 0x08, 0x82, 0x18,
	0xe1, 0xc4, 0x1d, 0x85, 0x70, 0x62, 0x12, 0x1b, 0xd8, 0x1c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x79, 0xf1, 0x1e, 0xef, 0xd5, 0x00, 0x00, 0x00,
}
